spring:
  application:
    name: news-app
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true


server:
  forward-headers-strategy: framework
  address: 0.0.0.0
  port: ${PORT:8080}

newsdata:
  api:
    key: abcd

gemini:
  api:
    key: AIzaSyDJ0EqRnDxjTegHX9lV9UD3mZvNe9VZjxQ


springdoc:
  swagger-ui:
    use-root-path: true

